return {
	"nvim-treesitter/nvim-treesitter",
	opts = {
		-- enable autotagging (w/ nvim-ts-autotag plugin)
		autotag = {
			enable = true,
		},
		-- ensure these language parsers are installed
		ensure_installed = {
			"asm",
			"awk",
			"bash",
			"c",
			"cpp",
			"cmake",
			"css",
			"csv",
      "cuda",
			"diff",
			"dot",
			"dockerfile",
			"gitignore",
			"git_config",
			"gitcommit",
			"git_rebase",
			"gitattributes",
			"html",
			"ini",
			"java",
			"javascript",
			"json",
			"jsdoc",
			"kdl",
			-- "latex",
			"linkerscript",
			"llvm",
			"lua",
			"luadoc",
			"luap",
      "make",
			"markdown",
			"markdown_inline",
			"matlab",
			"php",
			"perl",
			"python",
			"regex",
			"scala",
			"scss",
			"sql",
			"ssh_config",
			"tcl",
			"tmux",
			"toml",
			"typescript",
			"verilog",
			"vim",
			"vimdoc",
			"xml",
			"yaml",
		},
		keys = {
		 	{ "<c-enter>", desc = "Increment Selection", mode = { "x", "n" }},
		 	{ "<bs>", desc = "Decrement Selection", mode = "x" },
		 },
		 incremental_selection = {
		 	enable = true,
		 	-- Ctrl-Enter to incrementally select, backspace to incrementally deselect
		 	keymaps = {
		 		init_selection = "<c-enter>", -- set to `false` to disable one of the mappings
		 		node_incremental = "<c-enter>",
		 		scope_incremental = false,
		 		node_decremental = "<bs>",
		 	},
		 },
	},
}
